volumes:
  pg_data:

networks:
  router_net:

services:
  pg:
    image: postgres:15
    restart: unless-stopped

    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: hyperswitch_db

    volumes:
      - pg_data:/var/lib/postgresql/data

    networks:
      - router_net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d hyperswitch_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-standalone:
    image: redis:7-alpine
    restart: unless-stopped

    command: redis-server --appendonly yes

    networks:
      - router_net

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  superposition:
    image: ghcr.io/juspay/superposition-demo:0.102.0
    restart: unless-stopped

    environment:
      API_HOSTNAME: http://localhost:8081
      REDIS_URL: redis://redis-standalone:6379

    ports:
      - "8081:8080"

    depends_on:
      redis-standalone:
        condition: service_healthy

    networks:
      - router_net

  hyperswitch-server:
    image: docker.juspay.io/juspaydotin/hyperswitch-router:standalone
    restart: unless-stopped

    command: /local/bin/router -f /local/config/docker_compose.toml

    ports:
      - "8085:8080"

    volumes:
      - ./config:/local/config

    depends_on:
      pg:
        condition: service_healthy

      redis-standalone:
        condition: service_healthy

      superposition:
        condition: service_started

    networks:
      - router_net

    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
    environment:
      RUN_ENV: development

      ROUTER__MASTER_DATABASE__USERNAME: db_user
      ROUTER__MASTER_DATABASE__PASSWORD: db_pass
      ROUTER__MASTER_DATABASE__HOST: pg
      ROUTER__MASTER_DATABASE__PORT: 5432
      ROUTER__MASTER_DATABASE__DBNAME: hyperswitch_db

      ROUTER__REPLICA_DATABASE__USERNAME: db_user
      ROUTER__REPLICA_DATABASE__PASSWORD: db_pass
      ROUTER__REPLICA_DATABASE__HOST: pg
      ROUTER__REPLICA_DATABASE__PORT: 5432
      ROUTER__REPLICA_DATABASE__DBNAME: hyperswitch_db
